language: objective-c
cache:
  directories:
    - deps/src
    - deps/emsdk_portable
before_install:
  - brew update
  - brew install ninja
  - sudo easy_install virtualenv
env:
  - PLATFORM=mac CONF=debug
  - PLATFORM=mac CONF=release
  - PLATFORM=ios CONF=debug
  - PLATFORM=ios CONF=release
  - PLATFORM=emscripten CONF=debug
  - PLATFORM=emscripten CONF=release
script:
  - python rwconfig.py -p $PLATFORM
  - cd out/$CONF && ninja -v && if [ "$PLATFORM" = "mac" ]; then ./rw_tests; fi
