language: objective-c
cache:
  directories:
    - deps/src
    - deps/emsdk_portable
before_install:
  - brew update
  - brew install ninja
  - sudo ln -s /usr/bin/python2.7 /usr/bin/python2
  - export LLVM=`pwd`/deps/emsdk_portable/clang/e1.13.0_64bit
env:
  - PLATFORM=mac CONF=debug
  - PLATFORM=mac CONF=release
  - PLATFORM=ios CONF=debug
  - PLATFORM=ios CONF=release
  - PLATFORM=emscripten CONF=debug
  - PLATFORM=emscripten CONF=release
script:
  - python rwconfig.py -p $PLATFORM
  - cd out/$CONF && ninja -v && if [ "$PLATFORM" = "mac" ]; then ./rw_tests; fi
